site_name: "Vamsi Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "Vamsi Karuturi"
site_url: "https://vamsilabs-dev-notes.netlify.app"

# Repository
repo_name: "vamsi1998123/vamsilabs-dev-notes-main"
repo_url: "https://github.com/vamsi1998123/vamsilabs-dev-notes-main"

# Copyright
copyright: "Copyright &copy; 2020 - 2023 K Siva Prasad Reddy"

theme:
  name: material
nav:
  - Home: index.md
  - Learning: learning.md
  - Shortcuts: shortcuts.md
  - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md
      - Java Basics: java/Java Basics.md
  - StreamApi:
      - StreamApiQuestions: stream api/streamapi.md
  - SpringBoot:
      - Introduction: springboot/introduction.md
  - DevOps:
      - Tools: devops/devops.md
      - Linux: devops/linux.md
      - Docker: devops/docker.md
      - Ansible: devops/ansible.md
      - AWS: devops/aws.md
  - Misc:
      - CleanArchitecture: misc/clean-architecture.md

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/sivaprasadreddy"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/sivalabs"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/siva-prasad-reddy-katamreddy/"

# Extensions
markdown_extensions:
  - codehilite
  - tables
