site_name: "Vamsi Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "Vamsi Karuturi"
site_url: "https://vamsilabs-dev-notes.netlify.app"

repo_name: "vamsi1998123/vamsilabs-dev-notes-main"
repo_url: "https://github.com/vamsi1998123/vamsilabs-dev-notes-main"

theme:
  name: 'material'
  palette:
    primary: orange
    accent: cyan
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top  # Move navigation to the top of the page
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.autohide

nav:
  - Home: index.md
  - Learning: learning.md
  - Shortcuts: shortcuts.md
  - Git: git.md
  - Interview Questions: interviewquestions.md
  - DataStructures: dsa.md
  - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/vamsi1998123"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/vamsi-karuturi-2a117215b/"

# Extensions
markdown_extensions:
  - codehilite
  - tables
