site_name: "Vamsi Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "Vamsi Karuturi"
site_url: "https://vamsilabs-dev-notes.netlify.app"

repo_name: "vamsi1998123/vamsilabs-dev-notes-main"
repo_url: "https://github.com/vamsi1998123/vamsilabs-dev-notes-main"

theme:
  name: material
  palette:
    primary: "teal"
    accent: "lime"
  features:
    - tabs
    - search.highlight
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - header.autohide
    - search.share

#  features:
#    - search.highlight
#    - navigation.top
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.tracking
#    - navigation.expand
#    - navigation.path
#    - navigation.prune
#    - navigation.indexes
##    - header.autohide
#    - search.share
#    - content.tabs.link
#    - content.code.annotation
#    - content.code.copy
#
#extra_css:
#  - docs/custom/custom.css
#
#
#hide:
#  - navigation
#  - path






markdown_extensions:
  - codehilite
  - tables
  - attr_list
  - admonition
  - footnotes
  - def_list   # https://michelf.ca/projects/php-markdown/extra/#def-list
  - meta
  - smarty:
      smart_angled_quotes: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc:
      baselevel: 2

plugins:
  - search


nav:
  - Home: index.md
  - Learning: learning.md
  - Shortcuts: shortcuts.md
  - Git: git.md
  - Interview Questions: interviewquestions.md
  - DataStructures: dsa.md
  - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md
      - Java Basics: java/JavaBasics.md
      - JVM: java/Jvm.md
      - OOPS: java/oops.md
      - Constructors: java/Constructors.md
      - This and Super: java/thisandSuper.md
      - Access Modifiers: java/AccessModifiers.md
      - Strings: java/Strings.md
      - Wrapper Classes: java/WrapperClasses.md
      - Cloning: java/Cloning.md
      - Garbage Collection: java/GarbageCollection.md
      - Serialization: java/Serialization.md
      - Java 8: java/Java8.md
  - Advanced Java:
      - Exception Handling: java/ExceptionHandling.md
      - Collections: java/Collections.md
      - Differences in Collections: java/DiffCollections.md
      - Concurrent Collections: java/ConcurrentCollections.md
      - MultiThreading: java/MultiThreading.md
  - StreamApi:
      - StreamApiQuestions: stream api/streamapi.md
  - Solid Principles:
      - Solid Principles: solidprinciples/solidprinciples.md
  - Design Patterns:
      - Introduction: designpatterns/dp.md
      - Creational Design Patterns:
          - Creational Design Patterns: designpatterns/creationalDesignPatterns/CreationalDesignPatterns.md
          - Singleton : designpatterns/creationalDesignPatterns/singletondesignpattern.md
          - Factory : designpatterns/creationalDesignPatterns/FactoryDesignPattern.md
          - Abstract Factory : designpatterns/creationalDesignPatterns/AbstractFactoryDesignPattern.md
          - Builder :  designpatterns/creationalDesignPatterns/BuilderDesignPattern.md
          - Prototype : designpatterns/creationalDesignPatterns/PrototypeDesignPattern.md
      - Structural Design Patterns:
          - FlyWeight : designpatterns/structuralDesignPatterns/flyweightdesignpattern.md
          - Facade : designpatterns/structuralDesignPatterns/facadedesignpattern.md
          - Decorator : designpatterns/structuralDesignPatterns/DecoratorDesignPattern.md
          - Proxy : designpatterns/structuralDesignPatterns/Proxydesignpattern.md
          - Composite : designpatterns/structuralDesignPatterns/CompositeDesignPattern.md
          - Adapter : designpatterns/structuralDesignPatterns/AdapterDesignPattern.md
          - Bridge :  designpatterns/structuralDesignPatterns/BridgeDesignPattern.md
      - Behavioural Design Patterns:
          - Observer: designpatterns/behaviouralDesignPatterns/ObserverDesignPattern.md
          - Strategy: designpatterns/behaviouralDesignPatterns/StrategyDp.md
          - Command: designpatterns/behaviouralDesignPatterns/CommandDp.md
          - Iterator: designpatterns/behaviouralDesignPatterns/Iterator.md
          - State: designpatterns/behaviouralDesignPatterns/StateDp.md
          - Template: designpatterns/behaviouralDesignPatterns/TemplateDp.md
          - Chain Of Responsibility: designpatterns/behaviouralDesignPatterns/ChainOfResponsibilityDesignPattern.md
          - Mediator: designpatterns/behaviouralDesignPatterns/MediatorDp.md
          - Memento:  designpatterns/behaviouralDesignPatterns/MementoDp.md
          - Visitor: designpatterns/behaviouralDesignPatterns/VisitorDp.md
          - Interpreter: designpatterns/behaviouralDesignPatterns/Interpreter.md
  - SpringBoot:
      - Introduction: springboot/introduction.md
      - AutoConfiguration: springboot/AutoConfiguration.md
      - Annotations: springboot/Annotations.md
      - IOC and Dependency Injection: springboot/SpringIOC.md
      - Rest API Best Practices: springboot/restapibestpractices.md
      - Spring Boot 3: springboot/SpringBoot3.md
  - Junit:
      - Basics: junit/junit.md
  - DataBases:
      - Neo4j: databases/neo4j.md
      - SQL: databases/sql.md
  - Kafka:
      - Kafka Basics: Kafka/kafka.md
  - Postgresql:
      - Replication & Sharding: postgresql/postgresql.md
  - MicroServices:
      - Basic Terminology: microservices/microservices.md
      - CQRS: CQRS.md
  - System Design:
      - Https: https.md
      - Cap Theorem: capTheorem.md
      - Rate Limiter: ratelimiting.md
      - Load Balancing: loadbalancer.md
      - Distributed Caching: distributedCaching.md
      - Redis: redis.md
  - DevOps:
      - Tools: devops/devops.md
      - Linux: devops/linux.md
      - Docker: devops/docker.md
      - Ansible: devops/ansible.md
      - AWS: devops/aws.md
  - Misc:
      - CleanArchitecture: misc/clean-architecture.md

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/vamsi1998123"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/vamsi-karuturi-2a117215b/"
#  annotate:
#    json: [.s2]
#  analytics:
#    provider: google
#    property: !ENV GOOGLE_ANALYTICS_KEY

