site_name: "Vamsi Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "Vamsi Karuturi"
site_url: "https://vamsilabs-dev-notes.netlify.app"

# Repository
repo_name: "vamsi1998123/vamsilabs-dev-notes-main"
repo_url: "https://github.com/vamsi1998123/vamsilabs-dev-notes-main"

# Copyright
copyright: "Copyright &copy; Vamsi Karuturi"

theme:
  name: material
nav:
  - Home: index.md
  - Learning: learning.md
  - Shortcuts: shortcuts.md
  - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md
      - Java Basics: java/Java Basics.md
      - Exception Handling: java/ExceptionHandling.md
  - StreamApi:
      - StreamApiQuestions: stream api/streamapi.md
  - Solid Principles:
      - Solid Principles: solidprinciples/solidprinciples.md
  - Design Patterns:
      - Creational Design Patterns: designpatterns/creationalDesignPatterns/CreationalDesignPatterns.md
      - Singleton Design Pattern: designpatterns/creationalDesignPatterns/singletondesignpattern.md
      - Factory Design Pattern: designpatterns/creationalDesignPatterns/FactoryDesignPattern.md
      - Structural Design Pattern: designpatterns/structuralDesignPatterns/intro.md

  - SpringBoot:
      - Introduction: springboot/introduction.md
  - DataBases:
      - Neo4j: databases/neo4j.md
  - DevOps:
      - Tools: devops/devops.md
      - Linux: devops/linux.md
      - Docker: devops/docker.md
      - Ansible: devops/ansible.md
      - AWS: devops/aws.md
  - Misc:
      - CleanArchitecture: misc/clean-architecture.md

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/vamsi1998123"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/vamsi-karuturi-2a117215b/"

# Extensions
markdown_extensions:
  - codehilite
  - tables
