site_name: "Vamsi Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "Vamsi Karuturi"
site_url: "https://vamsilabs-dev-notes.netlify.app"

# Repository
repo_name: "vamsi1998123/vamsilabs-dev-notes-main"
repo_url: "https://github.com/vamsi1998123/vamsilabs-dev-notes-main"

# Copyright
copyright: "Copyright &copy; Vamsi Karuturi"

theme:
  name: material
nav:
  - Home: index.md
  - Learning: learning.md
  - Shortcuts: shortcuts.md
  - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md
      - Java Basics: java/Java Basics.md
      - Java 8: java/Java8.md
      - Exception Handling: java/ExceptionHandling.md
      - Collections: java/Collections.md
      - Concurrent Collections: java/ConcurrentCollections.md
      - MultiThreading: java/MultiThreading.md
  - StreamApi:
      - StreamApiQuestions: stream api/streamapi.md
  - Solid Principles:
      - Solid Principles: solidprinciples/solidprinciples.md
  - Design Patterns:
      - Creational Design Patterns:
          - Creational Design Patterns: designpatterns/creationalDesignPatterns/CreationalDesignPatterns.md
          - Singleton : designpatterns/creationalDesignPatterns/singletondesignpattern.md
          - Factory : designpatterns/creationalDesignPatterns/FactoryDesignPattern.md
          - Abstarct Factory : designpatterns/creationalDesignPatterns/AbstractFactoryDesignPattern.md
          - Prototype : designpatterns/creationalDesignPatterns/PrototypeDesignPattern.md
      - Structural Design Patterns:
          - FlyWeight : designpatterns/structuralDesignPatterns/flyweightdesignpattern.md
          - Facade : designpatterns/structuralDesignPatterns/facadedesignpattern.md
          - Decorator : designpatterns/structuralDesignPatterns/DecoratorDesignPattern.md
          - Proxy : designpatterns/structuralDesignPatterns/Proxydesignpattern.md
          - Composite : designpatterns/structuralDesignPatterns/CompositeDesignPattern.md
          - Adapter : designpatterns/structuralDesignPatterns/AdapterDesignPattern.md
          - Bridge :  designpatterns/structuralDesignPatterns/BridgeDesignPattern.md


      - Behavioural Design Patterns:
          - Chain Of Responsibility: designpatterns/behaviouralDesignPatterns/ChainOfResponsibilityDesignPattern.md
          - Command: designpatterns/behaviouralDesignPatterns/CommandDp.md
          - Iterator: designpatterns/behaviouralDesignPatterns/Iterator.md
          - Mediator: designpatterns/behaviouralDesignPatterns/MediatorDp.md
          - Memento: designpatterns/behaviouralDesignPatterns/MementoDP.md
          - Observer: designpatterns/behaviouralDesignPatterns/ObserverDesignPattern.md
          - State: designpatterns/behaviouralDesignPatterns/StateDp.md
          - Strategy: designpatterns/behaviouralDesignPatterns/StrategyDp.md
          - Template: designpatterns/behaviouralDesignPatterns/TemplateDp.md
          - Visitor: designpatterns/behaviouralDesignPatterns/VisitorDp.md
          - Interpreter: designpatterns/behaviouralDesignPatterns/Interpreter.md
          - Null Object: designpatterns/behaviouralDesignPatterns/NullObject.md

  - SpringBoot:
      - Introduction: springboot/introduction.md
  - DataBases:
      - Neo4j: databases/neo4j.md
      - SQL: databases/sql.md
  - DevOps:
      - Tools: devops/devops.md
      - Linux: devops/linux.md
      - Docker: devops/docker.md
      - Ansible: devops/ansible.md
      - AWS: devops/aws.md
  - Misc:
      - CleanArchitecture: misc/clean-architecture.md

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/vamsi1998123"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/vamsi-karuturi-2a117215b/"

# Extensions
markdown_extensions:
  - codehilite
  - tables
