site_name: "Vamsi Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "Vamsi Karuturi"
site_url: "https://vamsilabs-dev-notes.netlify.app"

repo_name: "vamsi1998123/vamsilabs-dev-notes-main"
repo_url: "https://github.com/vamsi1998123/vamsilabs-dev-notes-main"

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  features:
    - navigation.tabs: {}
    - navigation.sections: {}
    - toc.integrate: {}
    - navigation.top: {}
    - search.suggest: {}
    - search.highlight: {}
    - content.tabs.link: {}
    - content.code.annotation: {}
    - content.code.copy: {}

nav:
  - Home: index.md
  - Learning: learning.md
  - Shortcuts: shortcuts.md
  - Git: git.md
  - Interview Questions: interviewquestions.md
  - DataStructures: dsa.md
  - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md
      - Java Basics: java/JavaBasics.md
      - JVM: java/Jvm.md
      - OOPS: java/oops.md
      - Constructors: java/Constructors.md
      - This and Super: java/thisandSuper.md
      - Access Modifiers: java/AccessModifiers.md
      - Strings: java/Strings.md
      - Wrapper Classes: java/WrapperClasses.md
      - Cloning: java/Cloning.md
      - Garbage Collection: java/GarbageCollection.md
      - Serialization: java/Serialization.md
      - Java 8: java/Java8.md
  # (Rest of your navigation hierarchy...)

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/vamsi1998123"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/vamsi-karuturi-2a117215b/"

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
