[build]
command = " npm install mkdocs build --config-file mkdocs.yml"
publish = "site"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, deploy the lighthouse report to a path under your site
[plugins.inputs.audits]
output_path = "reports/lighthouse.html"