[build]
command = "mkdocs build --config-file mkdocs1.yml"
publish = "site"
[[plugins]]
package = "@sentry/netlify-build-plugin"
[plugins.inputs]
sentryOrg = "personal-4c8d758ce"
sentryProject = "new"