version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 7070:80
    environment:
      WORDPRESS_DB_PASSWORD: admin

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test